---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-web
  namespace: hyehwan
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: color-web
  template:
    metadata:
      labels:
        app: color-web
    spec:
      containers:
        - name: color-web
          image: 52.79.48.121:30002/hyehwan/color-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-web
  namespace: hyehwan
spec:
  selector:
    app: color-web
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30099
      port: 80
      targetPort: 80
