---
apiVersion: v1
kind: Service
metadata:
  name: color-web
  namespace: hyehwan
spec:
  selector:
    app: color-web
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30088
      port: 80
      targetPort: 80
