---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: hyehwan
  labels:
    name: jenkins
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /home/share/nfs/jenkins
    server: 10.0.9.243
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: hyehwan
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: jenkins
